language: java
jdk:
  - openjdk11

branches:
  only:
    - main
cache:
  directories:
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - syt07100@gmail.com
