spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(62p2sxnu8Jvu1DTh1BS7tUjWtr44OeAZLqnPYn5bkupo3hbIV03nCmlySQ28hIXCi7DlgZ2xdoCqcJYN8xFYJOYiktWoccxfD6u/rpJ2IiEUdRw1q1mp2Z0rROOXJJ+9RIerEpjFtj3xvhyxMnlalAnpGKnGP5lho6YRf6TXJrucbf7h76lIP9tZXIdCBd+4)
    username: ENC(ZyNWKoQuMgw/qd5KmWYbMQ==)
    password: ENC(n2i4eOTyZCDQkg26NKJUvJR0N5FFxZ9l)
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: minsu

server:
  port: 80

